from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QWidget, QMessageBox, QApplication

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 276)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_get_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_file.setMinimumSize(QtCore.QSize(140, 40))
        self.pushButton_get_file.setObjectName("pushButton_get_file")
        self.pushButton_get_file.clicked.connect(self.on_click_get_file)
        self.horizontalLayout_25.addWidget(self.pushButton_get_file)
        spacerItem = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.pushButton_save_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_result.setMinimumSize(QtCore.QSize(140, 40))
        self.pushButton_save_result.setObjectName("pushButton_save_result")
        self.horizontalLayout_25.addWidget(self.pushButton_save_result)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem1 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Q_gas_TM_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Q_gas_TM_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_Q_gas_TM_3.setObjectName("label_Q_gas_TM_3")
        self.horizontalLayout_4.addWidget(self.label_Q_gas_TM_3)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.lineEdit_Q_gas_TM_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Q_gas_TM_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_Q_gas_TM_3.setObjectName("lineEdit_Q_gas_TM_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_Q_gas_TM_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Q_gas_TM = QtWidgets.QLabel(self.centralwidget)
        self.label_Q_gas_TM.setMinimumSize(QtCore.QSize(50, 0))
        self.label_Q_gas_TM.setObjectName("label_Q_gas_TM")
        self.horizontalLayout_3.addWidget(self.label_Q_gas_TM)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.lineEdit_Q_gas_TM = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Q_gas_TM.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_Q_gas_TM.setObjectName("lineEdit_Q_gas_TM")
        self.horizontalLayout_3.addWidget(self.lineEdit_Q_gas_TM)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_Q_liq_TM = QtWidgets.QLabel(self.centralwidget)
        self.label_Q_liq_TM.setMinimumSize(QtCore.QSize(50, 0))
        self.label_Q_liq_TM.setObjectName("label_Q_liq_TM")
        self.horizontalLayout_8.addWidget(self.label_Q_liq_TM)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.lineEdit_Q_liq_TM = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Q_liq_TM.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_Q_liq_TM.setObjectName("lineEdit_Q_liq_TM")
        self.horizontalLayout_8.addWidget(self.lineEdit_Q_liq_TM)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Q_liq = QtWidgets.QLabel(self.centralwidget)
        self.label_Q_liq.setMinimumSize(QtCore.QSize(50, 0))
        self.label_Q_liq.setObjectName("label_Q_liq")
        self.horizontalLayout_5.addWidget(self.label_Q_liq)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.lineEdit_Q_liq = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Q_liq.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_Q_liq.setObjectName("lineEdit_Q_liq")
        self.horizontalLayout_5.addWidget(self.lineEdit_Q_liq)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_W_act = QtWidgets.QLabel(self.centralwidget)
        self.label_W_act.setMinimumSize(QtCore.QSize(50, 0))
        self.label_W_act.setObjectName("label_W_act")
        self.horizontalLayout_28.addWidget(self.label_W_act)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem6)
        self.lineEdit_W_act = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_W_act.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_W_act.setObjectName("lineEdit_W_act")
        self.horizontalLayout_28.addWidget(self.lineEdit_W_act)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_OBV_HAL = QtWidgets.QLabel(self.centralwidget)
        self.label_OBV_HAL.setMinimumSize(QtCore.QSize(50, 0))
        self.label_OBV_HAL.setObjectName("label_OBV_HAL")
        self.horizontalLayout_6.addWidget(self.label_OBV_HAL)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.lineEdit_OBV_HAL = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OBV_HAL.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_OBV_HAL.setObjectName("lineEdit_OBV_HAL")
        self.horizontalLayout_6.addWidget(self.lineEdit_OBV_HAL)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_N_d = QtWidgets.QLabel(self.centralwidget)
        self.label_N_d.setMinimumSize(QtCore.QSize(50, 0))
        self.label_N_d.setObjectName("label_N_d")
        self.horizontalLayout_2.addWidget(self.label_N_d)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.lineEdit_N_d = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_N_d.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_N_d.setObjectName("lineEdit_N_d")
        self.horizontalLayout_2.addWidget(self.lineEdit_N_d)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_P_zatr = QtWidgets.QLabel(self.centralwidget)
        self.label_P_zatr.setMinimumSize(QtCore.QSize(50, 0))
        self.label_P_zatr.setObjectName("label_P_zatr")
        self.horizontalLayout_7.addWidget(self.label_P_zatr)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.lineEdit_P_zatr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_P_zatr.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_P_zatr.setObjectName("lineEdit_P_zatr")
        self.horizontalLayout_7.addWidget(self.lineEdit_P_zatr)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_P_buf = QtWidgets.QLabel(self.centralwidget)
        self.label_P_buf.setMinimumSize(QtCore.QSize(50, 0))
        self.label_P_buf.setObjectName("label_P_buf")
        self.horizontalLayout_17.addWidget(self.label_P_buf)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.lineEdit_P_buf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_P_buf.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_P_buf.setObjectName("lineEdit_P_buf")
        self.horizontalLayout_17.addWidget(self.lineEdit_P_buf)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_D = QtWidgets.QLabel(self.centralwidget)
        self.label_D.setMinimumSize(QtCore.QSize(50, 0))
        self.label_D.setObjectName("label_D")
        self.horizontalLayout_18.addWidget(self.label_D)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.lineEdit_D = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_D.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_D.setObjectName("lineEdit_D")
        self.horizontalLayout_18.addWidget(self.lineEdit_D)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_29.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_P_lin = QtWidgets.QLabel(self.centralwidget)
        self.label_P_lin.setMinimumSize(QtCore.QSize(50, 0))
        self.label_P_lin.setObjectName("label_P_lin")
        self.horizontalLayout_19.addWidget(self.label_P_lin)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.lineEdit_P_lin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_P_lin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_P_lin.setObjectName("lineEdit_P_lin")
        self.horizontalLayout_19.addWidget(self.lineEdit_P_lin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_KVCH_HAL = QtWidgets.QLabel(self.centralwidget)
        self.label_KVCH_HAL.setMinimumSize(QtCore.QSize(50, 0))
        self.label_KVCH_HAL.setObjectName("label_KVCH_HAL")
        self.horizontalLayout_20.addWidget(self.label_KVCH_HAL)
        spacerItem13 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.lineEdit_KVCH_HAL = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_KVCH_HAL.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_KVCH_HAL.setObjectName("lineEdit_KVCH_HAL")
        self.horizontalLayout_20.addWidget(self.lineEdit_KVCH_HAL)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_I = QtWidgets.QLabel(self.centralwidget)
        self.label_I.setMinimumSize(QtCore.QSize(50, 0))
        self.label_I.setObjectName("label_I")
        self.horizontalLayout_21.addWidget(self.label_I)
        spacerItem14 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem14)
        self.lineEdit_I = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_I.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_I.setObjectName("lineEdit_I")
        self.horizontalLayout_21.addWidget(self.lineEdit_I)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_F = QtWidgets.QLabel(self.centralwidget)
        self.label_F.setMinimumSize(QtCore.QSize(50, 0))
        self.label_F.setObjectName("label_F")
        self.horizontalLayout_22.addWidget(self.label_F)
        spacerItem15 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem15)
        self.lineEdit_F = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_F.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_F.setObjectName("lineEdit_F")
        self.horizontalLayout_22.addWidget(self.lineEdit_F)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_Q_n = QtWidgets.QLabel(self.centralwidget)
        self.label_Q_n.setMinimumSize(QtCore.QSize(50, 0))
        self.label_Q_n.setObjectName("label_Q_n")
        self.horizontalLayout_23.addWidget(self.label_Q_n)
        spacerItem16 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem16)
        self.lineEdit_Q_n = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Q_n.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_Q_n.setObjectName("lineEdit_Q_n")
        self.horizontalLayout_23.addWidget(self.lineEdit_Q_n)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_29.addLayout(self.verticalLayout_7)
        spacerItem17 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem17)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem18 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem18)
        self.pushButton_get_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_result.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_get_result.setObjectName("pushButton_get_result")
        self.pushButton_get_result.clicked.connect(self.on_click_get_result)
        self.horizontalLayout_26.addWidget(self.pushButton_get_result)
        spacerItem19 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem20 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem20)
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_27.addWidget(self.label_result)
        spacerItem21 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def on_click_get_file(self):
        file, _ = QFileDialog.getOpenFileName(None, 'Выбрать файл с исходными данными для нейросети', './', "Dataset (*.csv *.xls)")

    def on_click_get_result(self):
        # msg = QMessageBox()
        # msg.setIcon(QMessageBox.Information)
        # msg.setWindowTitle("Результат")
        # msg.setText("По заданным параметрам значение вероятности отказа составляет 13,34%.")
        # retval = msg.exec_()

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setWindowTitle("Ошибка при вводе данных")
        msg.setText("Некорректные данные.\nЗначение Wакт должно быть численным!")
        retval = msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вероятность отказа УЭЦН"))
        self.pushButton_get_file.setText(_translate("MainWindow", "Выбрать данные\nдля обучения модели"))
        self.pushButton_save_result.setText(_translate("MainWindow", "Сохранить\nрезультаты"))
        self.label_Q_gas_TM_3.setText(_translate("MainWindow", "№ насоса"))
        self.lineEdit_Q_gas_TM_3.setText(_translate("MainWindow", "488"))
        self.label_Q_gas_TM.setText(_translate("MainWindow", "Qгаз тм"))
        self.lineEdit_Q_gas_TM.setText(_translate("MainWindow", "3.1684"))
        self.label_Q_liq_TM.setText(_translate("MainWindow", "Qж тм"))
        self.lineEdit_Q_liq_TM.setText(_translate("MainWindow", "0.2526"))
        self.label_Q_liq.setText(_translate("MainWindow", "Qж"))
        self.lineEdit_Q_liq.setText(_translate("MainWindow", "14,5"))
        self.label_W_act.setText(_translate("MainWindow", "Wакт"))
        self.lineEdit_W_act.setText(_translate("MainWindow", "1,5601"))
        self.label_OBV_HAL.setText(_translate("MainWindow", "Обв-ХАЛ"))
        self.lineEdit_OBV_HAL.setText(_translate("MainWindow", "38,8499"))
        self.label_N_d.setText(_translate("MainWindow", "Hд"))
        self.lineEdit_N_d.setText(_translate("MainWindow", "669,1428"))
        self.label_P_zatr.setText(_translate("MainWindow", "Pзатр"))
        self.lineEdit_P_zatr.setText(_translate("MainWindow", "3"))
        self.label_P_buf.setText(_translate("MainWindow", "Pбуф"))
        self.lineEdit_P_buf.setText(_translate("MainWindow", "2,5714"))
        self.label_D.setText(_translate("MainWindow", "Dшт"))
        self.lineEdit_D.setText(_translate("MainWindow", "12"))
        self.label_P_lin.setText(_translate("MainWindow", "Pлин"))
        self.lineEdit_P_lin.setText(_translate("MainWindow", "4,6666"))
        self.label_KVCH_HAL.setText(_translate("MainWindow", "КВЧ-ХАЛ"))
        self.lineEdit_KVCH_HAL.setText(_translate("MainWindow", "5,14285"))
        self.label_I.setText(_translate("MainWindow", "I"))
        self.lineEdit_I.setText(_translate("MainWindow", "8,3333"))
        self.label_F.setText(_translate("MainWindow", "F"))
        self.lineEdit_F.setText(_translate("MainWindow", "33,3333"))
        self.label_Q_n.setText(_translate("MainWindow", "Qн"))
        self.lineEdit_Q_n.setText(_translate("MainWindow", "2,7614"))
        self.pushButton_get_result.setText(_translate("MainWindow", "Получить\nвероятность"))
        self.label_result.setText(_translate("MainWindow", "Вероятность отказа составляет 13,34%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
